image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cabal v2-update
      stack build

    command: |
      stack test

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell

ports:
  - port: 8000
    onOpen: open-preview
